version: 0.2

env:
  variables:
    DOCKER_APP_NAME: sst-test-ecr-repository-production
    JOB_DEFINITION_NAME: tcdx-prd-hello-theater-schedule-batch-job-def
    DIRECTORY_NAME: hono-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version || (echo "Failed to execute aws --version" && exit 1)
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text) || (echo "Failed to retrieve AWS account ID" && exit 1)
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin https://${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com || (echo "Docker login failed" && exit 1)
      # - echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f ${DIRECTORY_NAME}/Dockerfile -t ${DOCKER_APP_NAME} ${DIRECTORY_NAME}
      # - docker build -f ${DIRECTORY_NAME}/Dockerfile --platform linux/arm64 -t ${DOCKER_APP_NAME} ${DIRECTORY_NAME}
  build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker tag ${DOCKER_APP_NAME}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/${DOCKER_APP_NAME}:latest || (echo "Docker tag failed" && exit 1)
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/${DOCKER_APP_NAME}:latest || (echo "Docker push failed" && exit 1)
  # post_build:
  #   commands:
  #     - cat ${DIRECTORY_NAME}/job-definition-template.json | jq --arg IMAGE_URI ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/${DOCKER_APP_NAME}:latest '.image|=$IMAGE_URI' > ${DIRECTORY_NAME}/job-definition.json
  #     - cat ${DIRECTORY_NAME}/job-definition.json
  #     - aws batch register-job-definition --job-definition-name $JOB_DEFINITION_NAME --type container --container-properties file://${DIRECTORY_NAME}/job-definition.json --platform-capabilities '[ "FARGATE" ]'
