version: 0.2

env:
  variables:
    AWS_REGION: "ap-northeast-1"
    IMAGE_TAG: "latest"
    INFRA_ID_PREFIX: "sst-test"
    APP_STAGE: "production"

phases:
  install:
    commands:
      - echo "Installing dependencies"

  pre_build:
    runtime-versions:
      docker: 20
    commands:
      - echo "Retrieving ECR repository URI"
      - export ECR_REPO_URI=$(aws ecr describe-repositories --query "repositories[?repositoryName=='${INFRA_ID_PREFIX}-ecr-repository-${APP_STAGE}'].repositoryUri" --output text)
      - if [ -z "$ECR_REPO_URI" ]; then echo "ERROR: ECR repository not found!" && exit 1; fi
      - echo "ECR Repository URI: $ECR_REPO_URI"
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$ECR_REPO_URI"

  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t "$ECR_REPO_URI:$IMAGE_TAG" -f hono-app/Dockerfile hono-app/

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR"
      - docker push "$ECR_REPO_URI:$IMAGE_TAG"
      - echo "Docker image pushed: $ECR_REPO_URI:$IMAGE_TAG"
      - echo "Writing image URI to file"
      - echo "{\"imageUri\":\"$ECR_REPO_URI:$IMAGE_TAG\"}" > imageDetail.json
      - cat imageDetail.json

artifacts:
  files:
    - imageDetail.json
