version: 0.2

env:
  variables:
    AWS_REGION: "ap-northeast-1" # AWSのリージョン
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies"

  pre_build:
    commands:
      - echo "Retrieving ECR repository URI"
      - ECR_REPO_URI=$(aws ecr describe-repositories --query "repositories[?repositoryName=='${INFRA_ID_PREFIX}-ecr-repository-${APP_STAGE}'].repositoryUri" --output text)
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG -f hono-app/Dockerfile hono-app/

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR"
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo "Docker image pushed: $ECR_REPO_URI:$IMAGE_TAG"
      - echo "Writing image URI to file"
      - echo "{\"imageUri\":\"$ECR_REPO_URI:$IMAGE_TAG\"}" > imageDetail.json
      - cat imageDetail.json

artifacts:
  files:
    - imageDetail.json
